version: '3'
services:
  app:
    image: ghcr.io/raka-yuda/foodmap:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3004:3000"
    env_file:
      - .env.production
    restart: unless-stopped